### ISSUE TITLE
OS X Ruby Issues

### ISSUE THREAD

**Issue by jurecuhalev** [CodeCatz/codecatz-tutorial#15]
Couple of issues

There needs to be an extra step where user enters `gcc` into command line, to force OS X to install Developer Tools. This has to happen before `gem install` because, otherwise installation fails due to missing headers.

`gem install github-pages` should be `sudo gem install github-pages`. The step itself also takes a while without visual feedback, so a note should be made of that.

After installation is done, `jeklly` is not in PATH yet, so user should open new window/tab.

**Comment by ialja** [comment]
Added instructions on how to install Xcode Command Line Tools in #38 and the sudo part was added already back in #18 

This gem install part has also been expanded to include info to wait, so I think all issues have been addressed.
