### ISSUE TITLE
Standardize Writing Style

### ISSUE THREAD

**Issue by ashocka** [CodeCatz/codecatz-tutorial#17]
We need to standardize how the tutorial parts are written. For example, in **[Part 1](http://codecatz.org/codecatz-tutorial/1-installation/)**, each step is prefaced with **Step #**. In other tutorials, there are no mentions of "steps".

It may be a good idea to either keep or drop those.

Also in some tutorials, H1 is used for each steps troughout the entire tutorial part, while in others, H2 takes its place.

I suggest H1 is used only for the page title, H2 for each of the steps, and H3, H4, etc. for any sub-headlines (and explanations). Makes it easier for styling and it's much better for SEO.

**Comment by ialja** [comment]
Good suggestions! Not sure what to do about steps, but I certainly agree we should either keep them or remove them. On one hand, it might be useful to have some sort of numbering on the page, so you can be clear about where you got stuck, but on the other hand, all those numbers can seem a bit too technical and off-putting :thought_balloon: 

Also agree with the headings suggestions.
