### ISSUE TITLE
Page #3 TODO

### ISSUE THREAD

**Issue by ashocka** [CodeCatz/codecatz-tutorial#25]
I noticed there's a part on page [3](http://codecatz.org/codecatz-tutorial/3-pages/) that needs expanding marked with

> // TODO: expand this section with View Source, Inspect Element …

**Comment by ialja** [comment]
Good to have a reminder :) Just cam across a link that could be useful, perhaps for the "read more" section: https://blog.udemy.com/learn-html-learn-the-foundations-of-html/ so I'll leave it here for when we expand this todo.
