### ISSUE TITLE
Explain that multiple terminals can be opened

### ISSUE THREAD

**Issue by goranche** [CodeCatz/codecatz-tutorial#9]
while going through the tutorial, at least two terminal windows will be open (one running jekyll, the other for ... well, entering other commands), a section explaining this might come in handy...
not sure where to put this, though :blush:

**Comment by goranche** [comment]
also, here's hoping that I didn't write this too soon and it's actually explained later on :angel:

**Comment by goranche** [comment]
oh... I see, we're going with the "run and stop" method... might actually be more beginner friendly :thought_balloon: 

I'm ok with this being closed... or left as an option...

**Comment by ialja** [comment]
Don't think we'll need other stuff :) Will close this for now, I don't think we should put too many "oh, by the way ..." non essential information in this tutorial, as it just might overwhelm them.
